<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/bot.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
  <div id="bot" class="border">
    <p>"{{ $t('hello') }}" is hello in {{ $t('language') }}</p>
    <select v-model="$i18n.locale">
      <option v-for="(lang, i) in langs" :key="`Lang${i}`" :value="lang">{{ lang }}</option>
    </select>
  </div>
</template>

<script>
export default {
  data: function() {
    return {
      langs: [
        'ml',
        'uk',
        'th',
        'es',
        'da',
        'pt',
        'de',
        'it',
        'pa',
        'pl',
        'gr',
        'en',
        'kr',
        'ru',
        'se',
        'jp',
        'fr',
        'cn',
        'vn',
        'ta'
      ]
    };
  }
};
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}

#bot {
  width: 400px;
  height: 400px;
}

.border {
  border: 1px solid #d1d1d1;
}
</style>
