// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./bot')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import App from '@/bot.vue'
import locale from 'locales/locale'

document.addEventListener('DOMContentLoaded', () => {
  console.log(locale)
  document.body.appendChild(document.createElement('bot'))
  const bot = new Vue({
    i18n: locale,
    render: h => h(App)
  }).$mount('bot')
  console.log({bot})
})
