// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Generate these JSON locales by running command: rails vue:translate
// Import the created JSON locales after running vue:translate command

import ml from "./ml.json";
import uk from "./uk.json";
import th from "./th.json";
import es from "./es.json";
import da from "./da.json";
import pt from "./pt.json";
import de from "./de.json";
import it from "./it.json";
import pa from "./pa.json";
import pl from "./pl.json";
import gr from "./gr.json";
import en from "./en.json";
import kr from "./kr.json";
import ru from "./ru.json";
import se from "./se.json";
import jp from "./jp.json";
import fr from "./fr.json";
import cn from "./cn.json";
import vn from "./vn.json";
import ta from "./ta.json";

const messages = {
...ml,
...uk,
...th,
...es,
...da,
...pt,
...de,
...it,
...pa,
...pl,
...gr,
...en,
...kr,
...ru,
...se,
...jp,
...fr,
...cn,
...vn,
...ta,
};
import Vue from "vue";
import VueI18n from "vue-i18n";
Vue.use(VueI18n);

const i18n = new VueI18n({
  locale: "en",
  messages
});

export default i18n;
